#! /bin/bash

DIRECT=/home/jc2545/scratch60/hj/thyroiditis/thyroiditis_noncoding/enhancer_promoter/v8
cd ${DIRECT}


# Annovar annotation
/home/jc2545/programs/annovar_20191024/table_annovar.pl --vcfinput /home/jc2545/scratch60/hj/thyroiditis/thyroiditis_noncoding/enhancer_promoter/v8/thy_genome_calls_pass_n17_decomposed_normalized.tmp.vcf /home/jc2545/programs/annovar/humandb/ -buildver hg19 -out /home/jc2545/scratch60/hj/thyroiditis/thyroiditis_noncoding/enhancer_promoter/v7/thy_genome_calls_pass_n17_decomposed_normalized_anno -remove -protocol refGeneWithVer,cytoBand,genomicSuperDups,bed,bed,bed,bed,bed,bed,bed,bed,bed,bed,bed,bed,intervar_20180118,clinvar_20210501,hgmd,gnomad211_exome,gnomad211_genome,gnomad_r2.1.1_merged,gnomad_r2.1_merged_hom,bravo_v8,kaviar_20150923,gene4denovo201907,medexome,xgen,dbnsfp42a,cadd13,spliceai,primateAI,dbscsnv11,regsnpintron,pext_all,uorf_stop,uorf_uaug,jarvis -operation gx,r,r,r,r,r,r,r,r,r,r,r,r,r,r,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f --bedfile hg19_gnomad_noncoding_zscore.bed,hg19_encode_CTCF_only.bed,hg19_encode_DNase_H3K4me3.bed,hg19_encode_PLS.bed,hg19_encode_cCREs.bed,hg19_encode_dELS.bed,hg19_encode_pELS.bed,hg19_ChromHMM_GM12878.bed,hg19_ChromHMM_H1_hESC.bed,hg19_ChromHMM_NHLF.bed,hg19_vista_enhancers.bed,hg19_fantom5_enhancers.bed -arg ',,,-colsWanted 4,-colsWanted 4,-colsWanted 4,-colsWanted 4,-colsWanted 4,-colsWanted 4,-colsWanted 4,-colsWanted 4,-colsWanted 4,-colsWanted 4,-colsWanted 4,-colsWanted 4,,,,,,,,,,,,,,,,,,,,,,' -nastring . -polish -xreffile /home/jc2545/programs/annovar_apr162018/annovar/example/gene_fullxref_gnomad211_constraint_genelist.txt --thread 20

rm -f thy_genome_calls_pass_n17_decomposed_normalized.tmp.vcf


# edit annotated vcf file 
cat thy_genome_calls_pass_n17_decomposed_normalized_anno.hg19_multianno.vcf | sed 's/ID=bed,/ID=gnomad_constraint_zscore,/g' | sed 's/ID=bed2,/ID=encode_CTCF_only,/g' | sed 's/ID=bed3,/ID=encode_DNase_H3K4me3,/g' | sed 's/ID=bed4,/ID=encode_PLS,/g' | sed 's/ID=bed5,/ID=encode_cCREs,/g' | sed 's/ID=bed6,/ID=encode_dELS,/g' | sed 's/ID=bed7,/ID=encode_pELS,/g' | sed 's/ID=bed8,/ID=ChromHMM_GM12878,/g' | sed 's/ID=bed9,/ID=ChromHMM_H1_hESC,/g' | sed 's/ID=bed10,/ID=ChromHMM_NHLF,/g' | sed 's/ID=bed11,/ID=vista_enhancers,/g' | sed 's/ID=bed12,/ID=fantom5_enhancers,/g' | sed 's/bed=/gnomad_constraint_zscore=/g' | sed 's/bed2=/encode_CTCF_only=/g' | sed 's/bed3=/encode_DNase_H3K4me3=/g' | sed 's/bed4=/encode_PLS=/g' | sed 's/bed5=/encode_cCREs=/g' | sed 's/bed6=/encode_dELS=/g' | sed 's/bed7=/encode_pELS=/g' | sed 's/bed8=/ChromHMM_GM12878=/g' | sed 's/bed9=/ChromHMM_H1_hESC=/g' | sed 's/bed10=/ChromHMM_NHLF=/g' | sed 's/bed11=/vista_enhancers=/g' | sed 's/bed12=/fantom5_enhancers=/g' | sed 's/Name\\x3d//g' > thy_genome_calls_pass_n17_decomposed_normalized_anno.hg19_multianno_edit.vcf
